name: 🚀 Release Please

on:
  push:
    branches:
      - main

concurrency: release-please

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # The following jobs are executed only if a release is created
  build-and-publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    strategy:
      fail-fast: false
      matrix:
        keycloak_version:
          - keycloak-26.6.2
          - keycloak-26.5.7
          - keycloak-26.4.7
          - keycloak-26.3.5
          - keycloak-26.2.5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: build-keycloak-spi
        run: |
          mvn -B clean package \
            -P"${{ matrix.keycloak_version }}" \
            -D"buildVersion=${{ needs.release-please.outputs.tag_name }}"

      - id: jar-filepath-step
        run: echo "jar-filepath=$(find target -type f -name "*.jar" ! -name "original-*")" >> $GITHUB_OUTPUT

      - name: Validate JAR file path
        run: |
          if [ -z "${{ steps.jar-filepath-step.outputs.jar-filepath }}" ]; then
            echo "Error: JAR file not found."
            exit 1
          fi

      - uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      - run: cosign version

      - name: Sign JARs with Cosign
        run: |
          cosign sign-blob --yes ${{ steps.jar-filepath-step.outputs.jar-filepath }} \
            --bundle ${{ steps.jar-filepath-step.outputs.jar-filepath }}.bundle

      - name: Upload file to release
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} ${{ steps.jar-filepath-step.outputs.jar-filepath }}
          gh release upload ${{ needs.release-please.outputs.tag_name }} ${{ steps.jar-filepath-step.outputs.jar-filepath }}.bundle
        env:
          GH_TOKEN: ${{ github.TOKEN }}
